### ISSUE TITLE
Picker für Erinnerungszeiten fehlerhaft

### ISSUE THREAD

**Issue by Zacherl** [SufficientlySecure/birthday-calendar#83]
Wenn die Zeiten der Erinnerung geändert werden, indem auf die Stunden oder Minuten geklickt und per Tastatur ein neuer Wert eingegeben wird, wird die Änderung nicht gespeichert.
Eine Änderung der Zeiten durch Benutzung der Pfeile (Stunden/Minuten inkrementieren/dekrementieren) wird korrekt übernommen.

Beobachtet auf einem Samsung Galaxy SIII mit Android 4.3.

**Comment by dschuermann** [comment]
Klingt leider nach einem Bug in Samsung's Android 4.3 an dem ich nichts machen kann.
